#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database")]
public partial class dbDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InserttblAdmin(tblAdmin instance);
  partial void UpdatetblAdmin(tblAdmin instance);
  partial void DeletetblAdmin(tblAdmin instance);
  partial void InserttblProduct(tblProduct instance);
  partial void UpdatetblProduct(tblProduct instance);
  partial void DeletetblProduct(tblProduct instance);
  partial void InserttblUser(tblUser instance);
  partial void UpdatetblUser(tblUser instance);
  partial void DeletetblUser(tblUser instance);
  #endregion
	
	public dbDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DatabaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public dbDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dbDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tblAdmin> tblAdmins
	{
		get
		{
			return this.GetTable<tblAdmin>();
		}
	}
	
	public System.Data.Linq.Table<tblProduct> tblProducts
	{
		get
		{
			return this.GetTable<tblProduct>();
		}
	}
	
	public System.Data.Linq.Table<tblUser> tblUsers
	{
		get
		{
			return this.GetTable<tblUser>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAdmin")]
public partial class tblAdmin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _adminname;
	
	private string _Emailid;
	
	private string _Password;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnadminnameChanging(string value);
    partial void OnadminnameChanged();
    partial void OnEmailidChanging(string value);
    partial void OnEmailidChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
	
	public tblAdmin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adminname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string adminname
	{
		get
		{
			return this._adminname;
		}
		set
		{
			if ((this._adminname != value))
			{
				this.OnadminnameChanging(value);
				this.SendPropertyChanging();
				this._adminname = value;
				this.SendPropertyChanged("adminname");
				this.OnadminnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emailid", DbType="VarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Emailid
	{
		get
		{
			return this._Emailid;
		}
		set
		{
			if ((this._Emailid != value))
			{
				this.OnEmailidChanging(value);
				this.SendPropertyChanging();
				this._Emailid = value;
				this.SendPropertyChanged("Emailid");
				this.OnEmailidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblProduct")]
public partial class tblProduct : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pkpid;
	
	private string _proname;
	
	private decimal _price;
	
	private string _url_img;
	
	private string _descr;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpkpidChanging(int value);
    partial void OnpkpidChanged();
    partial void OnpronameChanging(string value);
    partial void OnpronameChanged();
    partial void OnpriceChanging(decimal value);
    partial void OnpriceChanged();
    partial void Onurl_imgChanging(string value);
    partial void Onurl_imgChanged();
    partial void OndescrChanging(string value);
    partial void OndescrChanged();
    #endregion
	
	public tblProduct()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pkpid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pkpid
	{
		get
		{
			return this._pkpid;
		}
		set
		{
			if ((this._pkpid != value))
			{
				this.OnpkpidChanging(value);
				this.SendPropertyChanging();
				this._pkpid = value;
				this.SendPropertyChanged("pkpid");
				this.OnpkpidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_proname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string proname
	{
		get
		{
			return this._proname;
		}
		set
		{
			if ((this._proname != value))
			{
				this.OnpronameChanging(value);
				this.SendPropertyChanging();
				this._proname = value;
				this.SendPropertyChanged("proname");
				this.OnpronameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(10,2) NOT NULL")]
	public decimal price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this.OnpriceChanging(value);
				this.SendPropertyChanging();
				this._price = value;
				this.SendPropertyChanged("price");
				this.OnpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url_img", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
	public string url_img
	{
		get
		{
			return this._url_img;
		}
		set
		{
			if ((this._url_img != value))
			{
				this.Onurl_imgChanging(value);
				this.SendPropertyChanging();
				this._url_img = value;
				this.SendPropertyChanged("url_img");
				this.Onurl_imgChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descr", DbType="VarChar(450) NOT NULL", CanBeNull=false)]
	public string descr
	{
		get
		{
			return this._descr;
		}
		set
		{
			if ((this._descr != value))
			{
				this.OndescrChanging(value);
				this.SendPropertyChanging();
				this._descr = value;
				this.SendPropertyChanged("descr");
				this.OndescrChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblUser")]
public partial class tblUser : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _pkeid;
	
	private string _uname;
	
	private string _password;
	
	private string _status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnpkeidChanging(string value);
    partial void OnpkeidChanged();
    partial void OnunameChanging(string value);
    partial void OnunameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
	
	public tblUser()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pkeid", DbType="VarChar(250) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string pkeid
	{
		get
		{
			return this._pkeid;
		}
		set
		{
			if ((this._pkeid != value))
			{
				this.OnpkeidChanging(value);
				this.SendPropertyChanging();
				this._pkeid = value;
				this.SendPropertyChanged("pkeid");
				this.OnpkeidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string uname
	{
		get
		{
			return this._uname;
		}
		set
		{
			if ((this._uname != value))
			{
				this.OnunameChanging(value);
				this.SendPropertyChanging();
				this._uname = value;
				this.SendPropertyChanged("uname");
				this.OnunameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
